// <auto-generated />
using MOVIEW.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MOVIEW.Migrations
{
    [DbContext(typeof(MoviewDbContext))]
    [Migration("20210809115311_movi")]
    partial class movi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MOVIEW.Models.Register", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.Property<string>("Location");

                    b.Property<int>("Password");

                    b.Property<string>("Username");

                    b.HasKey("id");

                    b.ToTable("registers");
                });
#pragma warning restore 612, 618
        }
    }
}
