// <auto-generated />
using MOVIEW.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MOVIEW.Migrations
{
    [DbContext(typeof(MoviewDbContext))]
    [Migration("20210910134102_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MOVIEW.Models.Movies", b =>
                {
                    b.Property<string>("strId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("strDescription")
                        .IsRequired();

                    b.Property<string>("strMovieName")
                        .IsRequired();

                    b.Property<string>("strPrice")
                        .IsRequired();

                    b.Property<string>("strimageurl");

                    b.HasKey("strId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MOVIEW.Models.Order_Db", b =>
                {
                    b.Property<string>("StrId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Movie_Id")
                        .IsRequired();

                    b.Property<string>("customer_Id");

                    b.HasKey("StrId");

                    b.ToTable("Order_Db");
                });

            modelBuilder.Entity("MOVIEW.Models.Register", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.Property<string>("Location");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("id");

                    b.ToTable("registers");
                });
#pragma warning restore 612, 618
        }
    }
}
