// <auto-generated />
using MOVIEW.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MOVIEW.Migrations
{
    [DbContext(typeof(MoviewDbContext))]
    partial class MoviewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MOVIEW.Models.Movies", b =>
                {
                    b.Property<string>("strId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("strDescription")
                        .IsRequired();

                    b.Property<string>("strMovieName")
                        .IsRequired();

                    b.Property<string>("strPrice")
                        .IsRequired();

                    b.Property<string>("strimageurl");

                    b.HasKey("strId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MOVIEW.Models.Register", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.Property<string>("Location");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("id");

                    b.ToTable("registers");
                });

            modelBuilder.Entity("MOVIEW.Models.TemporaryDatabase", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("movie_id")
                        .IsRequired();

                    b.Property<string>("user_id")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TemporaryDatabase");
                });

            modelBuilder.Entity("MOVIEW.Models.price", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("strMovieName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Order_Db");
                });
#pragma warning restore 612, 618
        }
    }
}
